[package]
name = "mhdexdb"
version = "0.1.0"
authors = ["Break Yang <breakds@gmail.com>"]

[lib]
name = "dexdb"
path = "src/lib.rs"

[dependencies]
rusqlite = "0.x"
lazy_static = "0.x"
rustc-serialize = "0.x"
